erDiagram

    topic {
        string title
        string description
    }

    article {
        string title
        text content
        datetime created_at
        datetime updated_at
    }

    comment {
        datetime created_at
        text message
    }

    user_topic_preference {
        boolean notifications_enabled
    }

    topic }|--o{ article: categorizes
    article ||--o{ comment: contains
    user ||--o{ article: writes
    user ||--o{ comment: writes
    user ||--o{ user_topic_preference: has
    topic ||--o{ user_topic_preference: selected_in
